export const LOAD_BOXES = 'LOAD_BOXES';
export const LOAD_BOXES_SUCCESS = 'LOAD_BOXES_SUCCESS';

export const CREATE_BOX = 'CREATE_BOX';
export const CREATE_BOX_SUCCESS = 'CREATE_BOX_SUCCESS';

export const DELETE_BOX = 'DELETE_BOX';
export const DELETE_BOX_SUCCESS = 'DELETE_BOX_SUCCESS';

export const EDIT_BOX = 'EDIT_BOX';
