export const LOAD_CARDS = 'LOAD_CARDS';
export const LOAD_CARDS_SUCCESS = 'LOAD_CARDS_SUCCESS';

export const LOAD_CARD = 'LOAD_CARD';
export const LOAD_CARD_SUCCESS = 'LOAD_CARD_SUCCESS';

export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';

export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';

export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
