export const LOAD_HUNCHES = 'LOAD_HUNCHES';
export const LOAD_HUNCHES_SUCCESS = 'LOAD_HUNCHES_SUCCESS';

export const LOAD_HUNCH = 'LOAD_HUNCH';
export const LOAD_HUNCH_SUCCESS = 'LOAD_HUNCH_SUCCESS';

export const CREATE_HUNCH = 'CREATE_HUNCH';
export const CREATE_HUNCH_SUCCESS = 'CREATE_HUNCH_SUCCESS';

export const UPDATE_HUNCH = 'UPDATE_HUNCH';
export const UPDATE_HUNCH_SUCCESS = 'UPDATE_HUNCH_SUCCESS';

export const DELETE_HUNCH = 'DELETE_HUNCH';
export const DELETE_HUNCH_SUCCESS = 'DELETE_HUNCH_SUCCESS';

export const EDIT_HUNCH = 'EDIT_HUNCH';

