export const LOAD_HUNCHES = 'LOAD_HUNCHES';
export const UNLOAD_HUNCHES = 'UNLOAD_HUNCHES';

export const LOAD_HUNCH = 'LOAD_HUNCH';
export const UNLOAD_HUNCH = 'UNLOAD_HUNCH';

export const FETCH_HUNCHES = 'FETCH_HUNCHES';
export const FETCH_HUNCHES_REQUEST = 'FETCH_HUNCHES_REQUEST';
export const FETCH_HUNCHES_SUCCESS = 'FETCH_HUNCHES_SUCCESS';
export const FETCH_HUNCHES_FAILURE = 'FETCH_HUNCHES_FAILURE';

export const CREATE_HUNCH = 'CREATE_HUNCH';
export const CREATE_HUNCH_REQUEST = 'CREATE_HUNCH_REQUEST';
export const CREATE_HUNCH_SUCCESS = 'CREATE_HUNCH_SUCCESS';
export const CREATE_HUNCH_FAILURE = 'CREATE_HUNCH_FAILURE';

export const UPDATE_HUNCH = 'UPDATE_HUNCH';
export const UPDATE_HUNCH_REQUEST = 'UPDATE_HUNCH_REQUEST';
export const UPDATE_HUNCH_SUCCESS = 'UPDATE_HUNCH_SUCCESS';
export const UPDATE_HUNCH_FAILURE = 'UPDATE_HUNCH_FAILURE';

export const DELETE_HUNCH = 'DELETE_HUNCH';
export const DELETE_HUNCH_REQUEST = 'DELETE_HUNCH_REQUEST';
export const DELETE_HUNCH_SUCCESS = 'DELETE_HUNCH_SUCCESS';
export const DELETE_HUNCH_FAILURE = 'DELETE_HUNCH_FAILURE';

export const BOOST_HUNCH_EDITOR = 'BOOST_HUNCH_EDITOR';
export const RESUME_HUNCH_EDITOR_MODAL = 'RESUME_HUNCH_EDITOR_MODAL';
export const CLEAR_HUNCH_EDITOR = 'CLEAR_HUNCH_EDITOR';
export const CLOSE_HUNCH_EDITOR_MODAL = 'CLOSE_HUNCH_EDITOR_MODAL';
