export const LOAD_BOXES = 'LOAD_BOXES';
export const UNLOAD_BOXES = 'UNLOAD_BOXES';

export const LOAD_BOX = 'LOAD_BOX';
export const UNLOAD_BOX = 'UNLOAD_BOX';

export const FETCH_BOXES_REQUEST = 'FETCH_BOXES_REQUEST';
export const FETCH_BOXES_SUCCESS = 'FETCH_BOXES_SUCCESS';
export const FETCH_BOXES_FAILURE = 'FETCH_BOXES_FAILURE';

export const FETCH_BOX_REQUEST = 'FETCH_BOX_REQUEST';
export const FETCH_BOX_SUCCESS = 'FETCH_BOX_SUCCESS';
export const FETCH_BOX_FAILURE = 'FETCH_BOX_FAILURE';

export const CREATE_BOX_REQUEST = 'CREATE_BOX_REQUEST';
export const CREATE_BOX_SUCCESS = 'CREATE_BOX_SUCCESS';
export const CREATE_BOX_FAILURE = 'CREATE_BOX_FAILURE';

export const UPDATE_BOX_REQUEST = 'UPDATE_BOX_REQUEST';
export const UPDATE_BOX_SUCCESS = 'UPDATE_BOX_SUCCESS';
export const UPDATE_BOX_FAILURE = 'UPDATE_BOX_FAILURE';

export const DELETE_BOX_REQUEST = 'DELETE_BOX_REQUEST';
export const DELETE_BOX_SUCCESS = 'DELETE_BOX_SUCCESS';
export const DELETE_BOX_FAILURE = 'DELETE_BOX_FAILURE';

export const BOOST_BOX_EDITOR = 'BOOST_BOX_EDITOR';
export const RESUME_BOX_EDITOR_MODAL = 'RESUME_BOX_EDITOR_MODAL';
export const CLEAR_BOX_EDITOR = 'CLEAR_BOX_EDITOR';
export const CLOSE_BOX_EDITOR_MODAL = 'CLOSE_BOX_EDITOR_MODAL';
